fix not including threshold coverage values in threshold calc
eastgenomics/athena pull request #13
Opened 2020-11-13 17:37 UTC by jethror1

Fixes bug where coverage bin values at the threshold weren't included in the threshold calculations resulting in occasionally under calculating coverage

2020-11-15 11:26 UTC, pep8speaks commented
Hello @jethror1! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`bin/coverage_report_single.py`](https://github.com/eastgenomics/athena/blob/f65731eb283193635c928e825e33d92b36c67756/bin/coverage_report_single.py):

> [Line 29:1](https://github.com/eastgenomics/athena/blob/f65731eb283193635c928e825e33d92b36c67756/bin/coverage_report_single.py#L29): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 394:80](https://github.com/eastgenomics/athena/blob/f65731eb283193635c928e825e33d92b36c67756/bin/coverage_report_single.py#L394): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)
> [Line 1303:17](https://github.com/eastgenomics/athena/blob/f65731eb283193635c928e825e33d92b36c67756/bin/coverage_report_single.py#L1303): [E116](https://duckduckgo.com/?q=pep8%20E116) unexpected indentation (comment)
> [Line 1303:17](https://github.com/eastgenomics/athena/blob/f65731eb283193635c928e825e33d92b36c67756/bin/coverage_report_single.py#L1303): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '

2020-11-16 11:49 UTC, mattgarner requested changes
> Reviewed 1 of 2 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/athena/13)* status: all files reviewed, 2 unresolved discussions (waiting on @jethror1)

___
*[bin/coverage_report_single.py, line 1179 at r2](https://reviewable.io/reviews/eastgenomics/athena/13#-MMFs4VH-MwwjI4h8aJX:-MMFs4VI8XNQnT7G_BCa:b9kph32) ([raw file](https://github.com/eastgenomics/athena/blob/9a75a40a66bad8389da96b9a618e39dd318506a4/bin/coverage_report_single.py#L1179)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
>             sub_threshold_stats[threshold] < 99
>         ) & (
>             sub_threshold_stats[threshold] >= 95)].index, threshold]
>         x99 = pd.IndexSlice[sub_threshold_stats.loc[(
>             sub_threshold_stats[threshold] >= 99)].index, threshold]
> ```
</details>

Could you explain the intended change in the PR so that I can assess this change against the intention?
___
*[bin/coverage_report_single.py, line 1211 at r2](https://reviewable.io/reviews/eastgenomics/athena/13#-MMFsa-h1d1pxb8sfOhG:-MMFsa-h1d1pxb8sfOhH:bbu3ikx) ([raw file](https://github.com/eastgenomics/athena/blob/9a75a40a66bad8389da96b9a618e39dd318506a4/bin/coverage_report_single.py#L1211)):*
> ```
> .set_uuid("low_exon_table")\
> ```
Please explain the intended change


<!-- Sent from Reviewable.io -->

2020-11-16 14:07 UTC, jethror1 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/athena/13)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @mattgarner)

___
*[bin/coverage_report_single.py, line 1179 at r2](https://reviewable.io/reviews/eastgenomics/athena/13#-MMFs4VH-MwwjI4h8aJX:-MMGN5do3bGr6Gcg31uJ:b-896fix) ([raw file](https://github.com/eastgenomics/athena/blob/9a75a40a66bad8389da96b9a618e39dd318506a4/bin/coverage_report_single.py#L1179)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
>             sub_threshold_stats[threshold] < 99
>         ) & (
>             sub_threshold_stats[threshold] >= 95)].index, threshold]
>         x99 = pd.IndexSlice[sub_threshold_stats.loc[(
>             sub_threshold_stats[threshold] >= 99)].index, threshold]
> ```
Could you explain the intended change in the PR so that I can assess this change against the intention?
</blockquote></details>

Done.
___
*[bin/coverage_report_single.py, line 1211 at r2](https://reviewable.io/reviews/eastgenomics/athena/13#-MMFsa-h1d1pxb8sfOhG:-MMGN6YQEL7MAeC0w1qa:b-896fix) ([raw file](https://github.com/eastgenomics/athena/blob/9a75a40a66bad8389da96b9a618e39dd318506a4/bin/coverage_report_single.py#L1211)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> .set_uuid("low_exon_table")\
> ```
Please explain the intended change
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-11-16 17:29 UTC, mattgarner approved these changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/athena/13)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-11-16 17:29 UTC, merged