Add parallelisation
eastgenomics/athena pull request #16
Opened 2020-11-30 09:21 UTC by jethror1

- Adds parallelisation to both generating single sample stats and full gene plots for super speedy running
- Fixes #15 - typo in readme

2020-11-30 09:21 UTC, pep8speaks commented
Hello @jethror1! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`bin/coverage_report_single.py`](https://github.com/eastgenomics/athena/blob/8f6a6479df568ab2fc6c0e07bc522304f9a33e0f/bin/coverage_report_single.py):

> [Line 18:1](https://github.com/eastgenomics/athena/blob/8f6a6479df568ab2fc6c0e07bc522304f9a33e0f/bin/coverage_report_single.py#L18): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file

2020-11-30 10:26 UTC, Yu-jinKim requested changes
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/athena/16)* status: all files reviewed, 7 unresolved discussions (waiting on @jethror1 and @mattgarner)

___
*[bin/coverage_report_single.py, line 15 at r1](https://reviewable.io/reviews/eastgenomics/athena/16#-MNNdC_6DIayH3lxMEGB:-MNNdC_6DIayH3lxMEGC:b-h11sa1) ([raw file](https://github.com/eastgenomics/athena/blob/8f6a6479df568ab2fc6c0e07bc522304f9a33e0f/bin/coverage_report_single.py#L15)):*
> ```Python
> # use agg instead of tkinter for pyplot backend
> matplotlib.use('agg')
> import matplotlib.image as mpimg
> ```

I thought you were not using those imports
___
*[bin/coverage_report_single.py, line 1497 at r1](https://reviewable.io/reviews/eastgenomics/athena/16#-MNNe9w52vy3Q0R28E5K:-MNNe9w52vy3Q0R28E5L:b-cbs4d7) ([raw file](https://github.com/eastgenomics/athena/blob/8f6a6479df568ab2fc6c0e07bc522304f9a33e0f/bin/coverage_report_single.py#L1497)):*
> ```Python
>         if int(args.cores) > num_cores:
>             print(
>                 "Number cores given: {}, but only {} are available.",
> ```

missing .format ?
___
*[bin/coverage_report_single.py, line 1541 at r1](https://reviewable.io/reviews/eastgenomics/athena/16#-MNNelgy0rzciwlDY9Lg:-MNNelgy0rzciwlDY9Lh:b4c1113) ([raw file](https://github.com/eastgenomics/athena/blob/8f6a6479df568ab2fc6c0e07bc522304f9a33e0f/bin/coverage_report_single.py#L1541)):*
> ```Python
> 
>         # split gene list equally for seperate processes
>         gene_array = np.array_split(np.array(genes), num_cores)
> ```

what if only one core is given, it is handled correctly? very niche but you know
___
*[bin/coverage_report_single.py, line 1550 at r1](https://reviewable.io/reviews/eastgenomics/athena/16#-MNNfAjgDzpPyV2fM1rA:-MNNfAjh4fPfE0Z0k7-Q:bb7phvt) ([raw file](https://github.com/eastgenomics/athena/blob/8f6a6479df568ab2fc6c0e07bc522304f9a33e0f/bin/coverage_report_single.py#L1550)):*
> ```Python
> 
>         with multiprocessing.Pool(num_cores) as pool:
>             # use a pool to spawn multiple proecsses
> ```

typo
___
*[bin/coverage_stats_single.py, line 406 at r1](https://reviewable.io/reviews/eastgenomics/athena/16#-MNNfN3y5BY7R3DczS4R:-MNNfN3y5BY7R3DczS4S:bc6o82g) ([raw file](https://github.com/eastgenomics/athena/blob/8f6a6479df568ab2fc6c0e07bc522304f9a33e0f/bin/coverage_stats_single.py#L406)):*
> ```Python
>         )
>         parser.add_argument(
>             '--cores', nargs='?', default=None,
> ```

Is there a lot of code duplicated between your files?
Might be good to start working on a "main" script
___
*[bin/coverage_stats_single.py, line 447 at r1](https://reviewable.io/reviews/eastgenomics/athena/16#-MNNfhu19LqEEZmngoZY:-MNNfhu19LqEEZmngoZZ:b-j6jvsq) ([raw file](https://github.com/eastgenomics/athena/blob/8f6a6479df568ab2fc6c0e07bc522304f9a33e0f/bin/coverage_stats_single.py#L447)):*
> ```Python
>         if int(args.cores) > num_cores:
>             print(
>                 "Number cores given: {}, but only {} are available.",
> ```

.format missing
___
*[bin/coverage_stats_single.py, line 465 at r1](https://reviewable.io/reviews/eastgenomics/athena/16#-MNNfg8T6UhU9_KRY1zn:-MNNfg8T6UhU9_KRY1zo:bb7phvt) ([raw file](https://github.com/eastgenomics/athena/blob/8f6a6479df568ab2fc6c0e07bc522304f9a33e0f/bin/coverage_stats_single.py#L465)):*
> ```Python
> 
>     with multiprocessing.Pool(num_cores) as pool:
>         # use a pool to spawn multiple proecsses
> ```

typo


<!-- Sent from Reviewable.io -->

2020-11-30 11:59 UTC, jethror1 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/athena/16)* status: 1 of 3 files reviewed, 7 unresolved discussions (waiting on @mattgarner and @Yu-jinKim)

___
*[bin/coverage_report_single.py, line 15 at r1](https://reviewable.io/reviews/eastgenomics/athena/16#-MNNdC_6DIayH3lxMEGB:-MNO-0GL48DNX37rZqzv:b-yjs399) ([raw file](https://github.com/eastgenomics/athena/blob/8f6a6479df568ab2fc6c0e07bc522304f9a33e0f/bin/coverage_report_single.py#L15)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

I thought you were not using those imports
</blockquote></details>

removing mpimg in run_stats branch, mpatches is needed for plot legend styling
___
*[bin/coverage_report_single.py, line 1497 at r1](https://reviewable.io/reviews/eastgenomics/athena/16#-MNNe9w52vy3Q0R28E5K:-MNO-BAh35DblgAk8zky:b-896fix) ([raw file](https://github.com/eastgenomics/athena/blob/8f6a6479df568ab2fc6c0e07bc522304f9a33e0f/bin/coverage_report_single.py#L1497)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

missing .format ?
</blockquote></details>

Done.
___
*[bin/coverage_report_single.py, line 1541 at r1](https://reviewable.io/reviews/eastgenomics/athena/16#-MNNelgy0rzciwlDY9Lg:-MNO-CYa2gp5624mnFj0:bewk3ux) ([raw file](https://github.com/eastgenomics/athena/blob/8f6a6479df568ab2fc6c0e07bc522304f9a33e0f/bin/coverage_report_single.py#L1541)):*
then everything will be in one array, if more processes are specified than genes available this will result in empty arrays:

>>> import numpy as np
>>> num_cores=1
>>> genes=["gene"]
>>> np.array_split(np.array(genes), num_cores)
[array(['gene'], dtype='<U4')]
>>> genes=["gene", "gene2"]
>>> np.array_split(np.array(genes), num_cores)
[array(['gene', 'gene2'], dtype='<U5')]
>>> num_cores=4
>>> np.array_split(np.array(genes), num_cores)
[array(['gene'], dtype='<U5'), array(['gene2'], dtype='<U5'), array([], dtype='<U5'), array([], dtype='<U5')]

in this case it will generate an empty df for those, and this is handled in all_gene_plots( ) where it returns an empty string to the "".join( )
___
*[bin/coverage_report_single.py, line 1550 at r1](https://reviewable.io/reviews/eastgenomics/athena/16#-MNNfAjgDzpPyV2fM1rA:-MNO0NnxES0zMzhvXI-j:b-896fix) ([raw file](https://github.com/eastgenomics/athena/blob/8f6a6479df568ab2fc6c0e07bc522304f9a33e0f/bin/coverage_report_single.py#L1550)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

typo
</blockquote></details>

Done.
___
*[bin/coverage_stats_single.py, line 406 at r1](https://reviewable.io/reviews/eastgenomics/athena/16#-MNNfN3y5BY7R3DczS4R:-MNO0OkJ7Kt2e2YqANAQ:b-wrj10g) ([raw file](https://github.com/eastgenomics/athena/blob/8f6a6479df568ab2fc6c0e07bc522304f9a33e0f/bin/coverage_stats_single.py#L406)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

Is there a lot of code duplicated between your files?
Might be good to start working on a "main" script
</blockquote></details>

thought about this and might do, will require lots of thinking and rewriting but would be good
___
*[bin/coverage_stats_single.py, line 447 at r1](https://reviewable.io/reviews/eastgenomics/athena/16#-MNNfhu19LqEEZmngoZY:-MNO0UmCD5nUJFb_BxCw:b-896fix) ([raw file](https://github.com/eastgenomics/athena/blob/8f6a6479df568ab2fc6c0e07bc522304f9a33e0f/bin/coverage_stats_single.py#L447)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

.format missing
</blockquote></details>

Done.
___
*[bin/coverage_stats_single.py, line 465 at r1](https://reviewable.io/reviews/eastgenomics/athena/16#-MNNfg8T6UhU9_KRY1zn:-MNO0VHs-cbvoxLx3VUT:b-896fix) ([raw file](https://github.com/eastgenomics/athena/blob/8f6a6479df568ab2fc6c0e07bc522304f9a33e0f/bin/coverage_stats_single.py#L465)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

typo
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-12-03 17:14 UTC, Yu-jinKim approved these changes
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/athena/16)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mattgarner)



<!-- Sent from Reviewable.io -->

2020-12-03 17:14 UTC, merged