First release
eastgenomics/athena pull request #6
Opened 2020-09-22 15:36 UTC by jethror1

2020-09-22 15:36 UTC, pep8speaks commented
Hello @jethror1! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`bin/coverage_report_single.py`](https://github.com/eastgenomics/eggd_coverage_report/blob/63890966315fbde9a10b3068e9b7340827ca7c55/bin/coverage_report_single.py):

> [Line 17:1](https://github.com/eastgenomics/eggd_coverage_report/blob/63890966315fbde9a10b3068e9b7340827ca7c55/bin/coverage_report_single.py#L17): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 18:1](https://github.com/eastgenomics/eggd_coverage_report/blob/63890966315fbde9a10b3068e9b7340827ca7c55/bin/coverage_report_single.py#L18): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 19:1](https://github.com/eastgenomics/eggd_coverage_report/blob/63890966315fbde9a10b3068e9b7340827ca7c55/bin/coverage_report_single.py#L19): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 20:1](https://github.com/eastgenomics/eggd_coverage_report/blob/63890966315fbde9a10b3068e9b7340827ca7c55/bin/coverage_report_single.py#L20): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 21:1](https://github.com/eastgenomics/eggd_coverage_report/blob/63890966315fbde9a10b3068e9b7340827ca7c55/bin/coverage_report_single.py#L21): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 22:1](https://github.com/eastgenomics/eggd_coverage_report/blob/63890966315fbde9a10b3068e9b7340827ca7c55/bin/coverage_report_single.py#L22): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 23:1](https://github.com/eastgenomics/eggd_coverage_report/blob/63890966315fbde9a10b3068e9b7340827ca7c55/bin/coverage_report_single.py#L23): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 25:1](https://github.com/eastgenomics/eggd_coverage_report/blob/63890966315fbde9a10b3068e9b7340827ca7c55/bin/coverage_report_single.py#L25): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 26:1](https://github.com/eastgenomics/eggd_coverage_report/blob/63890966315fbde9a10b3068e9b7340827ca7c55/bin/coverage_report_single.py#L26): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 27:1](https://github.com/eastgenomics/eggd_coverage_report/blob/63890966315fbde9a10b3068e9b7340827ca7c55/bin/coverage_report_single.py#L27): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 28:1](https://github.com/eastgenomics/eggd_coverage_report/blob/63890966315fbde9a10b3068e9b7340827ca7c55/bin/coverage_report_single.py#L28): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 122:5](https://github.com/eastgenomics/eggd_coverage_report/blob/63890966315fbde9a10b3068e9b7340827ca7c55/bin/coverage_report_single.py#L122): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 175:5](https://github.com/eastgenomics/eggd_coverage_report/blob/63890966315fbde9a10b3068e9b7340827ca7c55/bin/coverage_report_single.py#L175): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 235:5](https://github.com/eastgenomics/eggd_coverage_report/blob/63890966315fbde9a10b3068e9b7340827ca7c55/bin/coverage_report_single.py#L235): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 294:5](https://github.com/eastgenomics/eggd_coverage_report/blob/63890966315fbde9a10b3068e9b7340827ca7c55/bin/coverage_report_single.py#L294): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 427:5](https://github.com/eastgenomics/eggd_coverage_report/blob/63890966315fbde9a10b3068e9b7340827ca7c55/bin/coverage_report_single.py#L427): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 597:5](https://github.com/eastgenomics/eggd_coverage_report/blob/63890966315fbde9a10b3068e9b7340827ca7c55/bin/coverage_report_single.py#L597): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 669:5](https://github.com/eastgenomics/eggd_coverage_report/blob/63890966315fbde9a10b3068e9b7340827ca7c55/bin/coverage_report_single.py#L669): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 918:5](https://github.com/eastgenomics/eggd_coverage_report/blob/63890966315fbde9a10b3068e9b7340827ca7c55/bin/coverage_report_single.py#L918): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)

* In the file [`bin/coverage_run_stats.py`](https://github.com/eastgenomics/eggd_coverage_report/blob/63890966315fbde9a10b3068e9b7340827ca7c55/bin/coverage_run_stats.py):

> [Line 109:5](https://github.com/eastgenomics/eggd_coverage_report/blob/63890966315fbde9a10b3068e9b7340827ca7c55/bin/coverage_run_stats.py#L109): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 173:5](https://github.com/eastgenomics/eggd_coverage_report/blob/63890966315fbde9a10b3068e9b7340827ca7c55/bin/coverage_run_stats.py#L173): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 235:5](https://github.com/eastgenomics/eggd_coverage_report/blob/63890966315fbde9a10b3068e9b7340827ca7c55/bin/coverage_run_stats.py#L235): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 253:5](https://github.com/eastgenomics/eggd_coverage_report/blob/63890966315fbde9a10b3068e9b7340827ca7c55/bin/coverage_run_stats.py#L253): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)

* In the file [`bin/coverage_stats_single.py`](https://github.com/eastgenomics/eggd_coverage_report/blob/63890966315fbde9a10b3068e9b7340827ca7c55/bin/coverage_stats_single.py):

> [Line 71:9](https://github.com/eastgenomics/eggd_coverage_report/blob/63890966315fbde9a10b3068e9b7340827ca7c55/bin/coverage_stats_single.py#L71): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 104:9](https://github.com/eastgenomics/eggd_coverage_report/blob/63890966315fbde9a10b3068e9b7340827ca7c55/bin/coverage_stats_single.py#L104): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 107:5](https://github.com/eastgenomics/eggd_coverage_report/blob/63890966315fbde9a10b3068e9b7340827ca7c55/bin/coverage_stats_single.py#L107): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 207:5](https://github.com/eastgenomics/eggd_coverage_report/blob/63890966315fbde9a10b3068e9b7340827ca7c55/bin/coverage_stats_single.py#L207): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 278:5](https://github.com/eastgenomics/eggd_coverage_report/blob/63890966315fbde9a10b3068e9b7340827ca7c55/bin/coverage_stats_single.py#L278): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 336:5](https://github.com/eastgenomics/eggd_coverage_report/blob/63890966315fbde9a10b3068e9b7340827ca7c55/bin/coverage_stats_single.py#L336): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)

2020-09-22 16:36 UTC, jethror1 commented
Fixes #1

2020-09-27 14:54 UTC, mattgarner requested changes
> Reviewed 12 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_coverage_report/6)* status: all files reviewed, 25 unresolved discussions (waiting on @jethror1)

___
*[README.md, line 3 at r1](https://reviewable.io/reviews/eastgenomics/eggd_coverage_report/6#-MIEkUi-8ys-kLyVJa5S:-MIEkUi-8ys-kLyVJa5T:bvpgu8b) ([raw file](https://github.com/eastgenomics/eggd_coverage_report/blob/561f77c1a53927168806e0666786ab7d1cf3671a/README.md#L3)):*
> ```
> an  interactive
> ```
double space
___
*[bin/annotate_bed.sh, line 46 at r1](https://reviewable.io/reviews/eastgenomics/eggd_coverage_report/6#-MIEmPe1Ce8F3ANG8gw5:-MIEmPe1Ce8F3ANG8gw6:btlohpc) ([raw file](https://github.com/eastgenomics/eggd_coverage_report/blob/561f77c1a53927168806e0666786ab7d1cf3671a/bin/annotate_bed.sh#L46)):*
> ```
> ··········
> ```
whitespace
___
*[bin/annotate_bed.sh, line 56 at r1](https://reviewable.io/reviews/eastgenomics/eggd_coverage_report/6#-MIEmRwl0bjZ_3fp1H8Z:-MIEmRwm-sbw6gD9hqgO:b-kdary8) ([raw file](https://github.com/eastgenomics/eggd_coverage_report/blob/561f77c1a53927168806e0666786ab7d1cf3671a/bin/annotate_bed.sh#L56)):*
> ```
> ····
> ```
whitespace
___
*[bin/annotate_bed.sh, line 63 at r1](https://reviewable.io/reviews/eastgenomics/eggd_coverage_report/6#-MIEq9b_6WUJ0pae_x0c:-MIEq9ba2h-ZcaYFa6iS:b-gmo22e) ([raw file](https://github.com/eastgenomics/eggd_coverage_report/blob/561f77c1a53927168806e0666786ab7d1cf3671a/bin/annotate_bed.sh#L63)):*
> ```
> > $(tmp).txt
> ```
Is this supposed to be curly braces? Where is tmp defined?
___
*[bin/coverage_report_single.py, line 64 at r1](https://reviewable.io/reviews/eastgenomics/eggd_coverage_report/6#-MIEqj3a1eCkQNFH6KMj:-MIEqj3a1eCkQNFH6KMk:b627gde) ([raw file](https://github.com/eastgenomics/eggd_coverage_report/blob/561f77c1a53927168806e0666786ab7d1cf3671a/bin/coverage_report_single.py#L64)):*
> ```
> with open(single_template, 'r') as temp:
>             html_template = temp.read()
> ```
suggest using template not temp so it's clearer that this doesn't mean temporary
___
*[bin/coverage_report_single.py, line 87 at r1](https://reviewable.io/reviews/eastgenomics/eggd_coverage_report/6#-MIErDxC9KwNxHMNiNfG:-MIErDxC9KwNxHMNiNfH:bke9adc) ([raw file](https://github.com/eastgenomics/eggd_coverage_report/blob/561f77c1a53927168806e0666786ab7d1cf3671a/bin/coverage_report_single.py#L87)):*
> ```
> ········
> ```
whitespace
___
*[bin/coverage_report_single.py, line 91 at r1](https://reviewable.io/reviews/eastgenomics/eggd_coverage_report/6#-MIErGFcDhiD0vZ3eA8D:-MIErGFcDhiD0vZ3eA8E:b-24jlvk) ([raw file](https://github.com/eastgenomics/eggd_coverage_report/blob/561f77c1a53927168806e0666786ab7d1cf3671a/bin/coverage_report_single.py#L91)):*
> ```
> ············
> ```
whitespace
___
*[bin/coverage_report_single.py, line 134 at r1](https://reviewable.io/reviews/eastgenomics/eggd_coverage_report/6#-MIEsCCG4x9T6wajVUcN:-MIEsCCG4x9T6wajVUcO:b-kz0ysn) ([raw file](https://github.com/eastgenomics/eggd_coverage_report/blob/561f77c1a53927168806e0666786ab7d1cf3671a/bin/coverage_report_single.py#L134)):*
> ```
> string of HTML template
> ```
Does this mean the content of the html template stored as a string, or the path to the html template?
___
*[bin/coverage_report_single.py, line 211 at r1](https://reviewable.io/reviews/eastgenomics/eggd_coverage_report/6#-MIEtFSBE8x1fijlacZa:-MIEtFSBE8x1fijlacZb:bgni90o) ([raw file](https://github.com/eastgenomics/eggd_coverage_report/blob/561f77c1a53927168806e0666786ab7d1cf3671a/bin/coverage_report_single.py#L211)):*
> ```
>         snps = snps[
>             (snps.snp_pos >= snps.exon_start) & (snps.snp_pos <= snps.exon_end)
>         ]
> ```
Is there something somewhere which enforces that the snps vcf only contains snps? What if it contains indels. What if these span exon boundaries?
___
*[bin/coverage_report_single.py, line 275 at r1](https://reviewable.io/reviews/eastgenomics/eggd_coverage_report/6#-MIEu0281b9X6XXiuZPz:-MIEu0281b9X6XXiuZQ-:b6m19r6) ([raw file](https://github.com/eastgenomics/eggd_coverage_report/blob/561f77c1a53927168806e0666786ab7d1cf3671a/bin/coverage_report_single.py#L275)):*
> ```
> 'chrom': int,
> ```
X, Y etc as int?
___
*[bin/coverage_report_single.py, line 397 at r1](https://reviewable.io/reviews/eastgenomics/eggd_coverage_report/6#-MIEvGN5D-hCJsHOJLfv:-MIEvGN5D-hCJsHOJLfw:b-ks0tuk) ([raw file](https://github.com/eastgenomics/eggd_coverage_report/blob/561f77c1a53927168806e0666786ab7d1cf3671a/bin/coverage_report_single.py#L397)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> else:
>                 # if any plots have no coverage, just display empty plot
>                 # very hacky way by making data point transparent but
>                 # ¯\_(ツ)_/¯
> ```
</details>

Does this correctly discriminate between 0 coverage and no coverage data?
___
*[bin/coverage_report_single.py, line 615 at r1](https://reviewable.io/reviews/eastgenomics/eggd_coverage_report/6#-MIEw6d97OZq3xgfZFXI:-MIEw6d97OZq3xgfZFXJ:brqd20w) ([raw file](https://github.com/eastgenomics/eggd_coverage_report/blob/561f77c1a53927168806e0666786ab7d1cf3671a/bin/coverage_report_single.py#L615)):*
> ```
> thrshld = str(threshold) + "x"
> ```
perhaps
threshold = str(threshold) + "x"
to avoid the confusion of 2 similarly named threshold variables?
___
*[bin/coverage_report_single.py, line 700 at r1](https://reviewable.io/reviews/eastgenomics/eggd_coverage_report/6#-MIEwkEG8VLiklmhW1aa:-MIEwkEG8VLiklmhW1ab:b-9n0rcv) ([raw file](https://github.com/eastgenomics/eggd_coverage_report/blob/561f77c1a53927168806e0666786ab7d1cf3671a/bin/coverage_report_single.py#L700)):*
> ```
> thrshld = str(args.threshold) + "x"
> ```
as above
___
*[bin/coverage_report_single.py, line 721 at r1](https://reviewable.io/reviews/eastgenomics/eggd_coverage_report/6#-MIEwzrn8t3o7ChASwsY:-MIEwzrn8t3o7ChASwsZ:b-h15ppq) ([raw file](https://github.com/eastgenomics/eggd_coverage_report/blob/561f77c1a53927168806e0666786ab7d1cf3671a/bin/coverage_report_single.py#L721)):*
> ```
> 'chrom': int,
> ```
as above
___
*[bin/coverage_report_single.py, line 796 at r1](https://reviewable.io/reviews/eastgenomics/eggd_coverage_report/6#-MIExJpb6tuM7sGsCmZZ:-MIExJpb6tuM7sGsCmZ_:b-x1qscn) ([raw file](https://github.com/eastgenomics/eggd_coverage_report/blob/561f77c1a53927168806e0666786ab7d1cf3671a/bin/coverage_report_single.py#L796)):*
> ```
> covered_genes
> ```
perhaps 'fully_covered_genes' would be more meaningful?
___
*[bin/coverage_report_single.py, line 845 at r1](https://reviewable.io/reviews/eastgenomics/eggd_coverage_report/6#-MIExZ5jB6QUI6OVFFJZ:-MIExZ5jB6QUI6OVFFJ_:byhtrn6) ([raw file](https://github.com/eastgenomics/eggd_coverage_report/blob/561f77c1a53927168806e0666786ab7d1cf3671a/bin/coverage_report_single.py#L845)):*
> ```
>  # apply colours to coverage cell based on value, 0 is given solid red
> ```
Edge case: what if the coverage is very very low but not 0. Is it possible to end up with < 1 pixel and so have an empty 'plot' instead of the red 0 plot?
___
*[bin/coverage_report_single.py, line 884 at r1](https://reviewable.io/reviews/eastgenomics/eggd_coverage_report/6#-MIEy2jlEC6x5VPDfq3-:-MIEy2jlEC6x5VPDfq30:b-w5fe1r) ([raw file](https://github.com/eastgenomics/eggd_coverage_report/blob/561f77c1a53927168806e0666786ab7d1cf3671a/bin/coverage_report_single.py#L884)):*
> ```
> No SNPs present
> ```
Maybe something like
'No low coverage SNPs'
would be more accurate?
___
*[bin/coverage_report_single.py, line 891 at r1](https://reviewable.io/reviews/eastgenomics/eggd_coverage_report/6#-MIEyFQY01Lie8P1p7Y5:-MIEyFQY01Lie8P1p7Y6:b-1wbzuf) ([raw file](https://github.com/eastgenomics/eggd_coverage_report/blob/561f77c1a53927168806e0666786ab7d1cf3671a/bin/coverage_report_single.py#L891)):*
> ```
> "<b>No SNPs present</b>"
> ```
'No good coverage SNPs' ?
___
*[bin/coverage_stats_single.py, line 68 at r1](https://reviewable.io/reviews/eastgenomics/eggd_coverage_report/6#-MIEzI9f4SkXtKJJEZsr:-MIEzI9f4SkXtKJJE [...]

2020-09-27 21:16 UTC, jethror1 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_coverage_report/6)* status: 6 of 11 files reviewed, 25 unresolved discussions (waiting on @jethror1 and @mattgarner)

___
*[README.md, line 3 at r1](https://reviewable.io/reviews/eastgenomics/eggd_coverage_report/6#-MIEkUi-8ys-kLyVJa5S:-MIFtGB06vf1CIBHiEer:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_coverage_report/blob/561f77c1a53927168806e0666786ab7d1cf3671a/README.md#L3)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> an  interactive
> ```
double space
</blockquote></details>

Done.
___
*[bin/annotate_bed.sh, line 46 at r1](https://reviewable.io/reviews/eastgenomics/eggd_coverage_report/6#-MIEmPe1Ce8F3ANG8gw5:-MIFtXAd6AFV-SyuAR80:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_coverage_report/blob/561f77c1a53927168806e0666786ab7d1cf3671a/bin/annotate_bed.sh#L46)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> ··········
> ```
whitespace
</blockquote></details>

Done.
___
*[bin/annotate_bed.sh, line 56 at r1](https://reviewable.io/reviews/eastgenomics/eggd_coverage_report/6#-MIEmRwl0bjZ_3fp1H8Z:-MIFtro7AG00DupGuyk6:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_coverage_report/blob/561f77c1a53927168806e0666786ab7d1cf3671a/bin/annotate_bed.sh#L56)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> ····
> ```
whitespace
</blockquote></details>

Done.
___
*[bin/annotate_bed.sh, line 63 at r1](https://reviewable.io/reviews/eastgenomics/eggd_coverage_report/6#-MIEq9b_6WUJ0pae_x0c:-MIG-q5k-VIqinYVvtUQ:b5rnzau) ([raw file](https://github.com/eastgenomics/eggd_coverage_report/blob/561f77c1a53927168806e0666786ab7d1cf3671a/bin/annotate_bed.sh#L63)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> > $(tmp).txt
> ```
Is this supposed to be curly braces? Where is tmp defined?
</blockquote></details>

It is yes, tmp is required to pass to the 2nd bedtools intersect as it expects a file
___
*[bin/coverage_report_single.py, line 134 at r1](https://reviewable.io/reviews/eastgenomics/eggd_coverage_report/6#-MIEsCCG4x9T6wajVUcN:-MIG6-rMEyNy0nPyiGBx:bv1jgm3) ([raw file](https://github.com/eastgenomics/eggd_coverage_report/blob/561f77c1a53927168806e0666786ab7d1cf3671a/bin/coverage_report_single.py#L134)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> string of HTML template
> ```
Does this mean the content of the html template stored as a string, or the path to the html template?
</blockquote></details>

its the content of the template to insert variables in to and generate the report from
___
*[bin/coverage_report_single.py, line 211 at r1](https://reviewable.io/reviews/eastgenomics/eggd_coverage_report/6#-MIEtFSBE8x1fijlacZa:-MIG6A1s4GBvVvHD3zej:bvio3yp) ([raw file](https://github.com/eastgenomics/eggd_coverage_report/blob/561f77c1a53927168806e0666786ab7d1cf3671a/bin/coverage_report_single.py#L211)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
>         snps = snps[
>             (snps.snp_pos >= snps.exon_start) & (snps.snp_pos <= snps.exon_end)
>         ]
> ```
Is there something somewhere which enforces that the snps vcf only contains snps? What if it contains indels. What if these span exon boundaries?
</blockquote></details>

No there isn't, will add it to the list of things to think about
___
*[bin/coverage_report_single.py, line 275 at r1](https://reviewable.io/reviews/eastgenomics/eggd_coverage_report/6#-MIEu0281b9X6XXiuZPz:-MIG6MHDEKbPZ_bYTa83:b-nsw8u6) ([raw file](https://github.com/eastgenomics/eggd_coverage_report/blob/561f77c1a53927168806e0666786ab7d1cf3671a/bin/coverage_report_single.py#L275)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> 'chrom': int,
> ```
X, Y etc as int?
</blockquote></details>

that was dumb, thought i'd changed it before
___
*[bin/coverage_report_single.py, line 397 at r1](https://reviewable.io/reviews/eastgenomics/eggd_coverage_report/6#-MIEvGN5D-hCJsHOJLfv:-MIG8ytu6iVxjlQrhcph:b-4kck50) ([raw file](https://github.com/eastgenomics/eggd_coverage_report/blob/561f77c1a53927168806e0666786ab7d1cf3671a/bin/coverage_report_single.py#L397)):*
Nope, both are treat the same:

>>> import pandas as pd
>>> df = pd.DataFrame(columns=["cov"])
>>> df
Empty DataFrame
Columns: [cov]
Index: []
>>> sum(df["cov"])
0
>>> df.loc[0] = [0]
>>> df
  cov
0   0
>>> sum(df["cov"])
0
___
*[bin/coverage_report_single.py, line 615 at r1](https://reviewable.io/reviews/eastgenomics/eggd_coverage_report/6#-MIEw6d97OZq3xgfZFXI:-MIGANSF0tSVXhjlGso9:bn55k0r) ([raw file](https://github.com/eastgenomics/eggd_coverage_report/blob/561f77c1a53927168806e0666786ab7d1cf3671a/bin/coverage_report_single.py#L615)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> thrshld = str(threshold) + "x"
> ```
perhaps
threshold = str(threshold) + "x"
to avoid the confusion of 2 similarly named threshold variables?
</blockquote></details>

makes sense, changed them all to threshold
___
*[bin/coverage_report_single.py, line 721 at r1](https://reviewable.io/reviews/eastgenomics/eggd_coverage_report/6#-MIEwzrn8t3o7ChASwsY:-MIGAU_O-NeRUOYDX0d9:b-ugd7rp) ([raw file](https://github.com/eastgenomics/eggd_coverage_report/blob/561f77c1a53927168806e0666786ab7d1cf3671a/bin/coverage_report_single.py#L721)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> 'chrom': int,
> ```
as above
</blockquote></details>

dumb again
___
*[bin/coverage_report_single.py, line 796 at r1](https://reviewable.io/reviews/eastgenomics/eggd_coverage_report/6#-MIExJpb6tuM7sGsCmZZ:-MIGAufL5PZf6l04hTRZ:b-n9tkhd) ([raw file](https://github.com/eastgenomics/eggd_coverage_report/blob/561f77c1a53927168806e0666786ab7d1cf3671a/bin/coverage_report_single.py#L796)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> covered_genes
> ```
perhaps 'fully_covered_genes' would be more meaningful?
</blockquote></details>

changed
___
*[bin/coverage_report_single.py, line 845 at r1](https://reviewable.io/reviews/eastgenomics/eggd_coverage_report/6#-MIExZ5jB6QUI6OVFFJZ:-MIGBDaTDptCO-tRDLR1:b-exss0e) ([raw file](https://github.com/eastgenomics/eggd_coverage_report/blob/561f77c1a53927168806e0666786ab7d1cf3671a/bin/coverage_report_single.py#L845)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
>  # apply colours to coverage cell based on value, 0 is given solid red
> ```
Edge case: what if the coverage is very very low but not 0. Is it possible to end up with < 1 pixel and so have an empty 'plot' instead of the red 0 plot?
</blockquote></details>

good question, not sure how to test this as it would depend on resolution of the monitor. This is for colouring the low covered regions table in the threshold column cells, so even if it was a tiny amount of coverage so no red was displayed, it would still show the percentage (i.e. a row with 0.001% in) so should still be obvious it is low? Can increase making it solid red to slightly higher if you think it is necessary 
___
*[bin/coverage_report_single.py, line 884 at r1](https://reviewable.io/reviews/eastgenomics/eggd_coverage_report/6#-MIEy2jlEC6x5VPDfq3-:-MIGBuVY5Roxcd0Vft-F:b-n9tkhd) ([raw file](https://github.com/eastgenomics/eggd_coverage_report/blob/561f77c1a53927168806e0666786ab7d1cf3671a/bin/coverage_report_single.py#L884)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> No SNPs present
> ```
Maybe something like
'No low coverage SNPs'
would be more accurate?
</blockquote></details>

changed
___
*[bin/coverage_report_single.py, line 891 at r1](https://reviewable.io/reviews/eastgenomics/eggd_coverage_report/6#-MIEyFQY01Lie8P1p7Y5:-MIGC7dZCMQjvdvfeBH8:b-n9tkhd) ([raw file](https://github.com/eastgenomics/eggd_coverage_report/bl [...]

2020-09-27 21:45 UTC, jethror1 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_coverage_report/6)* status: 6 of 11 files reviewed, 25 unresolved discussions (waiting on @jethror1 and @mattgarner)

___
*[bin/coverage_report_single.py, line 64 at r1](https://reviewable.io/reviews/eastgenomics/eggd_coverage_report/6#-MIEqj3a1eCkQNFH6KMj:-MIGVmvW6CLovhAbZttE:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_coverage_report/blob/561f77c1a53927168806e0666786ab7d1cf3671a/bin/coverage_report_single.py#L64)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> with open(single_template, 'r') as temp:
>             html_template = temp.read()
> ```
suggest using template not temp so it's clearer that this doesn't mean temporary
</blockquote></details>

Done.
___
*[bin/coverage_report_single.py, line 700 at r1](https://reviewable.io/reviews/eastgenomics/eggd_coverage_report/6#-MIEwkEG8VLiklmhW1aa:-MIGWDOn7m-JVTj89IaF:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_coverage_report/blob/561f77c1a53927168806e0666786ab7d1cf3671a/bin/coverage_report_single.py#L700)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> thrshld = str(args.threshold) + "x"
> ```
as above
</blockquote></details>

Done.
___
*[bin/coverage_stats_single.py, line 68 at r1](https://reviewable.io/reviews/eastgenomics/eggd_coverage_report/6#-MIEzI9f4SkXtKJJEZsr:-MIGWOKC9KMuf6SkHGiU:b-djdahv) ([raw file](https://github.com/eastgenomics/eggd_coverage_report/blob/561f77c1a53927168806e0666786ab7d1cf3671a/bin/coverage_stats_single.py#L68)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

Maybe?  Would be a bit more effort to conditionally not display in the report, mosdepth now always outputs the requirements file with the build. Will check on not showing the whole line if build isn't given
</blockquote></details>

Changed this to just not display the text at all if the build isn't given


<!-- Sent from Reviewable.io -->

2020-09-27 21:45 UTC, jethror1 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_coverage_report/6)* status: 6 of 11 files reviewed, 25 unresolved discussions (waiting on @mattgarner)

___
*[bin/coverage_report_single.py, line 87 at r1](https://reviewable.io/reviews/eastgenomics/eggd_coverage_report/6#-MIErDxC9KwNxHMNiNfG:-MIGWoCZAP6FtTavrHct:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_coverage_report/blob/561f77c1a53927168806e0666786ab7d1cf3671a/bin/coverage_report_single.py#L87)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> ········
> ```
whitespace
</blockquote></details>

Done.
___
*[bin/coverage_report_single.py, line 91 at r1](https://reviewable.io/reviews/eastgenomics/eggd_coverage_report/6#-MIErGFcDhiD0vZ3eA8D:-MIGWlIk-gNtNTN2foTs:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_coverage_report/blob/561f77c1a53927168806e0666786ab7d1cf3671a/bin/coverage_report_single.py#L91)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> ············
> ```
whitespace
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2020-10-14 13:39 UTC, jethror1 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/athena/6)* status: 3 of 14 files reviewed, 25 unresolved discussions (waiting on @mattgarner)

___
*[bin/annotate_bed.sh, line 63 at r1](https://reviewable.io/reviews/eastgenomics/athena/6#-MIEq9b_6WUJ0pae_x0c:-MJbGdcA-RjpzaCrwrm7:b-896fix) ([raw file](https://github.com/eastgenomics/athena/blob/561f77c1a53927168806e0666786ab7d1cf3671a/bin/annotate_bed.sh#L63)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

It is yes, tmp is required to pass to the 2nd bedtools intersect as it expects a file
</blockquote></details>

Done.
___
*[bin/coverage_report_single.py, line 134 at r1](https://reviewable.io/reviews/eastgenomics/athena/6#-MIEsCCG4x9T6wajVUcN:-MJbGlmm3QlakMik4FNk:b-896fix) ([raw file](https://github.com/eastgenomics/athena/blob/561f77c1a53927168806e0666786ab7d1cf3671a/bin/coverage_report_single.py#L134)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

its the content of the template to insert variables in to and generate the report from
</blockquote></details>

Done.
___
*[bin/coverage_report_single.py, line 211 at r1](https://reviewable.io/reviews/eastgenomics/athena/6#-MIEtFSBE8x1fijlacZa:-MJbGqd16iesrs4cgu0T:bsf86og) ([raw file](https://github.com/eastgenomics/athena/blob/561f77c1a53927168806e0666786ab7d1cf3671a/bin/coverage_report_single.py#L211)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

No there isn't, will add it to the list of things to think about
</blockquote></details>

Report now handles variants in VCF that span exon boundaries defined in the input bed and separates these into a table
___
*[bin/coverage_report_single.py, line 275 at r1](https://reviewable.io/reviews/eastgenomics/athena/6#-MIEu0281b9X6XXiuZPz:-MJbH3BY9b2LP1GIOgRO:b-896fix) ([raw file](https://github.com/eastgenomics/athena/blob/561f77c1a53927168806e0666786ab7d1cf3671a/bin/coverage_report_single.py#L275)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

that was dumb, thought i'd changed it before
</blockquote></details>

Done.
___
*[bin/coverage_report_single.py, line 397 at r1](https://reviewable.io/reviews/eastgenomics/athena/6#-MIEvGN5D-hCJsHOJLfv:-MJbHCg3ByEmJBKZmTDq:b-896fix) ([raw file](https://github.com/eastgenomics/athena/blob/561f77c1a53927168806e0666786ab7d1cf3671a/bin/coverage_report_single.py#L397)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

Nope, both are treat the same:

>>> import pandas as pd
>>> df = pd.DataFrame(columns=["cov"])
>>> df
Empty DataFrame
Columns: [cov]
Index: []
>>> sum(df["cov"])
0
>>> df.loc[0] = [0]
>>> df
  cov
0   0
>>> sum(df["cov"])
0
</blockquote></details>

Done.
___
*[bin/coverage_report_single.py, line 615 at r1](https://reviewable.io/reviews/eastgenomics/athena/6#-MIEw6d97OZq3xgfZFXI:-MJbHF9lA3K8nzNujfd5:b-896fix) ([raw file](https://github.com/eastgenomics/athena/blob/561f77c1a53927168806e0666786ab7d1cf3671a/bin/coverage_report_single.py#L615)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

makes sense, changed them all to threshold
</blockquote></details>

Done.
___
*[bin/coverage_report_single.py, line 721 at r1](https://reviewable.io/reviews/eastgenomics/athena/6#-MIEwzrn8t3o7ChASwsY:-MJbHKGuDhsYfbvffOA2:b-896fix) ([raw file](https://github.com/eastgenomics/athena/blob/561f77c1a53927168806e0666786ab7d1cf3671a/bin/coverage_report_single.py#L721)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

dumb again
</blockquote></details>

Done.
___
*[bin/coverage_report_single.py, line 796 at r1](https://reviewable.io/reviews/eastgenomics/athena/6#-MIExJpb6tuM7sGsCmZZ:-MJbHN4yE7zTSB16MpYp:b-896fix) ([raw file](https://github.com/eastgenomics/athena/blob/561f77c1a53927168806e0666786ab7d1cf3671a/bin/coverage_report_single.py#L796)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

changed
</blockquote></details>

Done.
___
*[bin/coverage_report_single.py, line 845 at r1](https://reviewable.io/reviews/eastgenomics/athena/6#-MIExZ5jB6QUI6OVFFJZ:-MJbHTdZEc8qTV_4gvOu:b-896fix) ([raw file](https://github.com/eastgenomics/athena/blob/561f77c1a53927168806e0666786ab7d1cf3671a/bin/coverage_report_single.py#L845)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

good question, not sure how to test this as it would depend on resolution of the monitor. This is for colouring the low covered regions table in the threshold column cells, so even if it was a tiny amount of coverage so no red was displayed, it would still show the percentage (i.e. a row with 0.001% in) so should still be obvious it is low? Can increase making it solid red to slightly higher if you think it is necessary 
</blockquote></details>

Done.
___
*[bin/coverage_report_single.py, line 884 at r1](https://reviewable.io/reviews/eastgenomics/athena/6#-MIEy2jlEC6x5VPDfq3-:-MJbHV2Z31c5oM0UPBwB:b-896fix) ([raw file](https://github.com/eastgenomics/athena/blob/561f77c1a53927168806e0666786ab7d1cf3671a/bin/coverage_report_single.py#L884)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

changed
</blockquote></details>

Done.
___
*[bin/coverage_report_single.py, line 891 at r1](https://reviewable.io/reviews/eastgenomics/athena/6#-MIEyFQY01Lie8P1p7Y5:-MJbHVXI0xoIYeqcoicK:b-896fix) ([raw file](https://github.com/eastgenomics/athena/blob/561f77c1a53927168806e0666786ab7d1cf3671a/bin/coverage_report_single.py#L891)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

changed
</blockquote></details>

Done.
___
*[bin/coverage_stats_single.py, line 68 at r1](https://reviewable.io/reviews/eastgenomics/athena/6#-MIEzI9f4SkXtKJJEZsr:-MJbHaQH7V4kr2e1e7E5:b-896fix) ([raw file](https://github.com/eastgenomics/athena/blob/561f77c1a53927168806e0666786ab7d1cf3671a/bin/coverage_stats_single.py#L68)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

Changed this to just not display the text at all if the build isn't given
</blockquote></details>

Done.
___
*[bin/coverage_stats_single.py, line 175 at r1](https://reviewable.io/reviews/eastgenomics/athena/6#-MIEzcbeBXKRgKjd-ZK7:-MJbKEed3r4vn1q7TouS:b-896fix) ([raw file](https://github.com/eastgenomics/athena/blob/561f77c1a53927168806e0666786ab7d1cf3671a/bin/coverage_stats_single.py#L175)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

Coordinates - I believe so? Will check mosdepth docs
How is best to handle the assert? Just raise an exception and error if it is bad?
</blockquote></details>

Done.
___
*[bin/coverage_stats_single.py, line 191 at r1](https://reviewable.io/reviews/eastgenomics/athena/6#-MIF-wyX1VQRAMk3_G1F:-MJbHjPe3cTeYgz0X-3F:b-896fix) ([raw file](https://github.com/eastgenomics/athena/blob/561f77c1a53927168806e0666786ab7d1cf3671a/bin/coverage_stats_single.py#L191)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

changed to use math.floor, allows for limiting to 2dp instead of rounding:

>>> math.floor(99.999999 * 100) / 100
99.99
</blockquote></details>

Done.
___
*[bin/coverage_stats_single.py, line 273 at r1](https://reviewable.io/reviews/eastgenomics/athena/6#-MIF0FLe6gbR_sgJ0JXm:-MJbKGMs2Agi8bZhkOgb:b-896fix) ([raw file](https://github.com/eastgenomics/athena/blob/561f77c1a53927168806e0666786ab7d1cf3671a/bin/coverage_stats_single.py#L273)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

same as above
</blockquote></details>

Done.
___
*[bin/coverage_stats_single.py, line 280 at r1](https://reviewable.io/reviews/eastgenomics/athena/6#-MIF0dIn9IASACEa2i6P:-MJbKIHZET8tZOs1stnB:b-896fix) ([raw file](https://github.com/eastgenomics/athena/blob/561f77c1a53927168806e0666786ab7d1cf3671a/bin/coverage_stats_single.py#L280)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

changed
</blockquote></details>

Done.
___
*[o [...]

2020-10-15 18:12 UTC, mattgarner approved these changes
> Reviewed 1 of 6 files at r3, 12 of 13 files at r4.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/athena/6)* status: :shipit: complete! all files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2020-10-15 18:13 UTC, merged