v2 part 1
eastgenomics/athena pull request #84
Opened 2023-04-17 16:18 UTC by jethror1

First part of refactoring Athena to improve everything and allow for addition of run level coverage data.

Main changes:

-  calling of all parts of Athena has moved to `athena.py`, this allows for all commands to be run through a single set of arguments and flexibly control running sub commands (i.e. just stats or report) or going from raw data to report. Operations currently implemented are annotating of panel bed and generating of per sample stats (`_exon_stats.tsv` and `_gene_stats.tsv`)

- annotating of bed file with transcript / exon information and per base coverage values has moved to `bin/annotate.py`

- calculating of per sample coverage stats has moved to `bin/stats.py` , the main functions called in here are:
  - https://github.com/eastgenomics/athena/blob/2043d23bdc0bf06b790d925484293bcbc7346748/athena/bin/stats.py#L22
    - calls all functions to generate **exon** level stats, this is wrapped by `calculate_exon_stats_parallel`  to utilise all cores for speedy calculations
  - https://github.com/eastgenomics/athena/blob/2043d23bdc0bf06b790d925484293bcbc7346748/athena/bin/stats.py#L134
    - calls all functions to generate **gene** level stats

- cmd line args are in `bin/arguments.py` , each sub command arguments are in separate functions to make the many many arguments more readable (this will expand with run level stats and reports etc being added)

- readme hasn't been updated yet so can be ignored for now :)

2023-04-18 09:35 UTC, Yu-jinKim requested changes
> Reviewed 11 of 19 files at r1, 18 of 18 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/athena/84)* status: all files reviewed, 11 unresolved discussions (waiting on @JasonLing95 and @jethror1)

___
*[`athena/athena.py` line 55 at r2](https://reviewable.io/reviews/eastgenomics/athena/84#-NTIRYqN9eQK8HGNr6ti:-NTIRYqOBbExLnWVI7ex:b-vnigj) ([raw file](https://github.com/eastgenomics/athena/blob/a368bfe19bd19695ae68faf586440f9d9e314b59/athena/athena.py#L55)):*
> ```Python
> 
>         Args:
> ```

missing info on args, returns and outputs
___
*[`athena/athena.py` line 60 at r2](https://reviewable.io/reviews/eastgenomics/athena/84#-NTIRuMN9tB-EG_tjkTW:-NTIRuMN9tB-EG_tjkTX:b-utbijd) ([raw file](https://github.com/eastgenomics/athena/blob/a368bfe19bd19695ae68faf586440f9d9e314b59/athena/athena.py#L60)):*
> ```Python
>         Outputs:
>         """
>         exon_stats = stats.stats().calculate_exon_stats_parallel(
> ```

i hate that you have call that function using `stats.stats`
But that's a difference in philosophy
___
*[`athena/athena.py` line 89 at r2](https://reviewable.io/reviews/eastgenomics/athena/84#-NTIS9ck2s2f0XAyM2wj:-NTIS9ck2s2f0XAyM2wk:b-gxxh6l) ([raw file](https://github.com/eastgenomics/athena/blob/a368bfe19bd19695ae68faf586440f9d9e314b59/athena/athena.py#L89)):*
> ```Python
> 
>     if args.sub == 'annotate_bed_file':
>         # sub command to annotated target bed file with transcript/exon and
> ```

typo annotate
___
*[`athena/athena.py` line 152 at r2](https://reviewable.io/reviews/eastgenomics/athena/84#-NTIT0psEoQJW86SlSe0:-NTIT0psEoQJW86SlSe1:bnziw7t) ([raw file](https://github.com/eastgenomics/athena/blob/a368bfe19bd19695ae68faf586440f9d9e314b59/athena/athena.py#L152)):*
> ```Python
>         exon_stats.to_csv(
>             f"{args.output}_exon_stats.tsv",
>             sep='\t', index=False, mode=mode
> ```

any failsafe if `args.hsmetrics` is not provided?
___
*[`athena/athena.py` line 163 at r2](https://reviewable.io/reviews/eastgenomics/athena/84#-NTITE0y9cnwocfliYs2:-NTITE0y9cnwocfliYs3:b2quasx) ([raw file](https://github.com/eastgenomics/athena/blob/a368bfe19bd19695ae68faf586440f9d9e314b59/athena/athena.py#L163)):*
> ```Python
> 
>     elif args.sub == 'calculate_run_stats':
>         pass
> ```

i'm guessing that will be part 2?
___
*[`athena/bin/annotate.py` line 35 at r2](https://reviewable.io/reviews/eastgenomics/athena/84#-NTITPC_3JkEl9zWXgeQ:-NTITPC_3JkEl9zWXgeR:b-b5ezer) ([raw file](https://github.com/eastgenomics/athena/blob/a368bfe19bd19695ae68faf586440f9d9e314b59/athena/bin/annotate.py#L35)):*
> ```Python
> 
>         # turn dfs into BedTools objects
>         bed = bedtools.BedTool.from_dataframe(panel_bed)
> ```

it's weird to read bedtool
___
*[`athena/bin/annotate.py` line 138 at r2](https://reviewable.io/reviews/eastgenomics/athena/84#-NTIUBji2fw8i6rfDIpy:-NTIUBjj9btXIKmS5e1w:bco7n7o) ([raw file](https://github.com/eastgenomics/athena/blob/a368bfe19bd19695ae68faf586440f9d9e314b59/athena/bin/annotate.py#L138)):*
> ```Python
>         # check again for empty output of bedtools, can happen due to memory
>         # maxing out and doesn't seem to raise an exception...
>         assert len(bed_w_coverage) > 0, """Error intersecting with coverage
> ```

is there no error message if the issue is a memory limit?
___
*[`athena/bin/arguments.py` line 25 at r2](https://reviewable.io/reviews/eastgenomics/athena/84#-NTIUVjE6jBRMUpVE37O:-NTIUVjE6jBRMUpVE37P:b-kaa98z) ([raw file](https://github.com/eastgenomics/athena/blob/a368bfe19bd19695ae68faf586440f9d9e314b59/athena/bin/arguments.py#L25)):*
> ```Python
> def generic_arguments(parser):
>     """
>     Generic arguments not specific to any running mode
> ```

no info on arg
___
*[`athena/bin/load.py` line 87 at r2](https://reviewable.io/reviews/eastgenomics/athena/84#-NTIWtXkARL9DpFBjCTb:-NTIWtXkARL9DpFBjCTc:bsid8id) ([raw file](https://github.com/eastgenomics/athena/blob/a368bfe19bd19695ae68faf586440f9d9e314b59/athena/bin/load.py#L87)):*
> ```Python
>         # first test file has expected columns
>         with open(transcript_file, 'r') as f:
>             assert f.readline().count('\t') == 5, (
> ```

is that correct based on the error message?
___
*[`athena/bin/load.py` line 258 at r2](https://reviewable.io/reviews/eastgenomics/athena/84#-NTIbHIoBS7SkUdiIrM_:-NTIbHIoBS7SkUdiIrMa:bmio0xy) ([raw file](https://github.com/eastgenomics/athena/blob/a368bfe19bd19695ae68faf586440f9d9e314b59/athena/bin/load.py#L258)):*
> ```Python
>         metrics = []
> 
>         for idx, line in enumerate(contents):
> ```

why not integrate this with the `with open` above?
___
*[`athena/bin/load.py` line 297 at r2](https://reviewable.io/reviews/eastgenomics/athena/84#-NTIbQ_f3G1AB9YwCtDU:-NTIbQ_f3G1AB9YwCtDV:btbkrtn) ([raw file](https://github.com/eastgenomics/athena/blob/a368bfe19bd19695ae68faf586440f9d9e314b59/athena/bin/load.py#L297)):*
> ```Python
>         # low_stats = pd.DataFrame(columns=columns)
> 
>         # get all exons with <100% coverage at given threshold
> ```

delete unused lines of code


<!-- Sent from Reviewable.io -->

2023-04-18 10:32 UTC, JasonLing95 requested changes
> Reviewed 11 of 19 files at r1, 18 of 18 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/athena/84)* status: all files reviewed, 24 unresolved discussions (waiting on @jethror1)

___
*[`athena/athena.py` line 165 at r2](https://reviewable.io/reviews/eastgenomics/athena/84#-NTIl3vK8JzjGAp3e9xq:-NTIl3vK8JzjGAp3e9xr:bha7yz7) ([raw file](https://github.com/eastgenomics/athena/blob/a368bfe19bd19695ae68faf586440f9d9e314b59/athena/athena.py#L165)):*
> ```Python
>         pass
> 
>     elif args.sub == 'generate_report':
> ```

there'll be more here right? else this looks redundant



_Code quote:_
```Python
    elif args.sub == 'calculate_run_stats':
        pass

    elif args.sub == 'generate_report':
        pass

    else:
        pass
```
___
*[`athena/bin/annotate.py` line 80 at r2](https://reviewable.io/reviews/eastgenomics/athena/84#-NTIlvLx6zP7ifitvV4C:-NTIlvLx6zP7ifitvV4D:b-t8ir6x) ([raw file](https://github.com/eastgenomics/athena/blob/a368bfe19bd19695ae68faf586440f9d9e314b59/athena/bin/annotate.py#L80)):*
> ```Python
> 
> 
>     def add_coverage(self, bed_w_transcript, coverage_df, chunks=False):
> ```

might be better just to standardize the function to accept list[pd.DataFrame] rather than either list of df or df. Then deal with it with a for loop in both if else statement below since if not chunks, there'll only be one df in the list thus looped through once.



_Code quote:_
```Python
coverage_df
```
___
*[`athena/bin/utils.py` line 42 at r2](https://reviewable.io/reviews/eastgenomics/athena/84#-NTIuuou8zPvB7wJiKcD:-NTIuuou8zPvB7wJiKcE:b-fn9d7f) ([raw file](https://github.com/eastgenomics/athena/blob/a368bfe19bd19695ae68faf586440f9d9e314b59/athena/bin/utils.py#L42)):*
> ```Python
>     """
>     # generate list of single base values in range of coverage bins
>     binned_data['position'] = list(map(list, list(map(
> ```

is this generating
```
    chr  exon_start exon_end  gene      tx         exon cov_start  cov_end  cov position
    1    2488098    2488177  TNFRSF14  NM_003820.3  1    2488096   2488099  233 [2488096, 2488097, 2488098....]
```



_Code quote:_
```Python
    # generate list of single base values in range of coverage bins
    binned_data['position'] = list(map(list, list(map(
        range, binned_data['cov_start'].values,
        binned_data['cov_end'].values
    ))))
```
___
*[`athena/bin/load.py` line 15 at r2](https://reviewable.io/reviews/eastgenomics/athena/84#-NTImoDd7uw18baL2VVU:-NTImoDd7uw18baL2VVV:b-1jgay2) ([raw file](https://github.com/eastgenomics/athena/blob/a368bfe19bd19695ae68faf586440f9d9e314b59/athena/bin/load.py#L15)):*
> ```Python
> 
> 
> class loadData():
> ```

LoadData()



_Code quote:_
```Python
 loadData():
```
___
*[`athena/bin/load.py` line 59 at r2](https://reviewable.io/reviews/eastgenomics/athena/84#-NTIo0RA6ABGrt-dDFjM:-NTIo0RA6ABGrt-dDFjN:b5rs944) ([raw file](https://github.com/eastgenomics/athena/blob/a368bfe19bd19695ae68faf586440f9d9e314b59/athena/bin/load.py#L59)):*
> ```Python
>         # first test file has expected columns
>         with open(bed_file, 'r') as f:
>             assert f.readline().count('\t') == 3, (
> ```

doesn't readline() returns list of rows within the file? I'm not sure how counting the \t will give us the number of cols 
___
*[`athena/bin/load.py` line 71 at r2](https://reviewable.io/reviews/eastgenomics/athena/84#-NTInOXh9nPP_m04ts-8:-NTInOXh9nPP_m04ts-9:b-og5c1f) ([raw file](https://github.com/eastgenomics/athena/blob/a368bfe19bd19695ae68faf586440f9d9e314b59/athena/bin/load.py#L71)):*
> ```Python
>         # strip chr from chrom if present
>         panel_bed["chrom"] = panel_bed["chrom"].apply(
>             lambda x: str(x).replace("chr", "")
> ```

could do .strip() afterward just in case there're some outlier which end up with additional empty space after .replace()



_Code quote:_
```Python
str(x).replace("chr", "")
```
___
*[`athena/bin/load.py` line 99 at r2](https://reviewable.io/reviews/eastgenomics/athena/84#-NTIoWIh9h9xMehSFxSK:-NTIoWIh9h9xMehSFxSL:b-wkugkc) ([raw file](https://github.com/eastgenomics/athena/blob/a368bfe19bd19695ae68faf586440f9d9e314b59/athena/bin/load.py#L99)):*
> ```Python
>         # strip chr from chrom if present
>         transcript_info_df["chrom"] = transcript_info_df["chrom"].apply(
>             lambda x: str(x).replace("chr", "")
> ```

do a .strip() to eliminate potential empty space after replace



_Code quote:_
```Python
            lambda x: str(x).replace("chr", "")
        )
```
___
*[`athena/bin/load.py` line 105 at r2](https://reviewable.io/reviews/eastgenomics/athena/84#-NTIol830pc9IWVlAZ2q:-NTIol830pc9IWVlAZ2r:b-9nkahy) ([raw file](https://github.com/eastgenomics/athena/blob/a368bfe19bd19695ae68faf586440f9d9e314b59/athena/bin/load.py#L105)):*
> ```Python
> 
> 
>     def read_coverage_data(self, coverage_file, chunk_size=None):
> ```

if the above function is standardized to received list of df, then this function can be standardized to output only list of df - makes function a little straightforward



_Code quote:_
```Python
def read_coverage_data(self, coverage_file, chunk_size=None):
```
___
*[`athena/bin/load.py` line 169 at r2](https://reviewable.io/reviews/eastgenomics/athena/84#-NTIp1Xa3lQoBnwDvf1M:-NTIp1Xa3lQoBnwDvf1N:b4ezq7o) ([raw file](https://github.com/eastgenomics/athena/blob/a368bfe19bd19695ae68faf586440f9d9e314b59/athena/bin/load.py#L169)):*
> ```Python
>             # strip chr from chrom in cases of diff. formatted bed
>             cov_stats["chrom"] = cov_stats["chrom"].apply(
>                 lambda x: str(x).replace("chr", "")
> ```

strip()



_Code quote:_
```Python
.replace("chr", "")
```
___
*[`athena/bin/load.py` line 212 at r2](https://reviewable.io/reviews/eastgenomics/athena/84#-NTIp4s138R27hgdQFTy:-NTIp4s138R27hgdQFTz:b4ezq7o) ([raw file](https://github.com/eastgenomics/athena/blob/a368bfe19bd19695ae68faf586440f9d9e314b59/athena/bin/load.py#L212)):*
> ```Python
>         # strip chr from chrom in cases of diff. formatted bed
>         raw_coverage["chrom"] = raw_coverage["chrom"].apply(
>             lambda x: str(x).replace("chr", "")
> ```

strip()



_Code quote:_
```Python
x: str(x).replace("chr", "")
```
___
*[`athena/bin/load.py` line 228 at r2](https://reviewable.io/reviews/eastgenomics/athena/84#-NTIpICc0TXG-KsWF0HR:-NTIpICc0TXG-KsWF0HS:bq92gzl) ([raw file](https://github.com/eastgenomics/athena/blob/a368bfe19bd19695ae68faf586440f9d9e314b59/athena/bin/load.py#L228)):*
> ```Python
>             - html_template (str): report template
>         """
>         bin_dir = os.path.dirname(os.path.abspath(__file__))
> ```

BIN_DIR since it's static



_Code quote:_
```Python
bin_dir = os.path.dirname(os.path.abspath(__file__))
```
___
*[`athena/bin/load.py` line 339 at r2](https://reviewable.io/reviews/eastgenomics/athena/84#-NTIr4er45yAGRT3UrYo:-NTIr4er45yAGRT3UrYp:b-nmt47q) ([raw file](https://github.com/eastgenomics/athena/blob/a368bfe19bd19695ae68faf586440f9d9e314b59/athena/bin/load.py#L339)):*
> ```Python
>                                 {}</b></li>".format(reference)
>                         if "38" in build:
>                             build = "<li>Reference build used for aligment<b>\
> ```

can these two be one if clause? will there be a possibility that there's no 37 in reference?



_Code quote:_
```Python
                        if "37" in reference:
                            build = "<li>Reference build used for aligment<b>\
                                {}</b></li>".format(reference)
                        if "38" in build:
                            build = "<li>Reference build used for aligment<b>\
                                {}</b></li>".format(reference)
```
___
*[`athena/bin/load.py` line 368 at r2](https://reviewable.io/reviews/eastgenomics/athena/84#-NTIrP571feuj4fbpDlB:-NTIrP571feuj4fbpDlC:b-wod02c) ([raw file](https://github.com/eastgenomics/athena/blob/a368bfe19bd19695ae68faf586440f9d9e314b59/athen [...]

2023-04-18 16:59 UTC, jethror1 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/athena/84)* status: 24 of 32 files reviewed, 23 unresolved discussions (waiting on @JasonLing95 and @Yu-jinKim)

___
*[`athena/athena.py` line 55 at r2](https://reviewable.io/reviews/eastgenomics/athena/84#-NTIRYqN9eQK8HGNr6ti:-NTJCiqv2lBZTzghwFLN:b-896fix) ([raw file](https://github.com/eastgenomics/athena/blob/a368bfe19bd19695ae68faf586440f9d9e314b59/athena/athena.py#L55)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

missing info on args, returns and outputs
</blockquote></details>

Done.
___
*[`athena/athena.py` line 60 at r2](https://reviewable.io/reviews/eastgenomics/athena/84#-NTIRuMN9tB-EG_tjkTW:-NTJCjMkA7iWmJrkk0FG:bp0r84u) ([raw file](https://github.com/eastgenomics/athena/blob/a368bfe19bd19695ae68faf586440f9d9e314b59/athena/athena.py#L60)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

i hate that you have call that function using `stats.stats`
But that's a difference in philosophy
</blockquote></details>

switched this to be `stats.Sample()` since I've started on run stats in here too and named it as `stats.Run()`

I disliked it also but only realised when I imported it how it was named and was too lazy to change
___
*[`athena/athena.py` line 152 at r2](https://reviewable.io/reviews/eastgenomics/athena/84#-NTIT0psEoQJW86SlSe0:-NTJDWvX9dCWWTX4u9FK:b-95028z) ([raw file](https://github.com/eastgenomics/athena/blob/a368bfe19bd19695ae68faf586440f9d9e314b59/athena/athena.py#L152)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

any failsafe if `args.hsmetrics` is not provided?
</blockquote></details>

this is required when calculating run level stats to normalise per sample coverage against the per sample reads, if run level stats aren't being added then this isn't required to be passed. I will check for hsmetrics being present in the header of this file when generating the run stats (at some point I will write it all in the readme to explain it)
___
*[`athena/athena.py` line 163 at r2](https://reviewable.io/reviews/eastgenomics/athena/84#-NTITE0y9cnwocfliYs2:-NTJDQef5SP2dz5NTOap:b-f1av7i) ([raw file](https://github.com/eastgenomics/athena/blob/a368bfe19bd19695ae68faf586440f9d9e314b59/athena/athena.py#L163)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

i'm guessing that will be part 2?
</blockquote></details>

yeah was just mapping out whats coming in other PRs for structure in my head
___
*[`athena/athena.py` line 165 at r2](https://reviewable.io/reviews/eastgenomics/athena/84#-NTIl3vK8JzjGAp3e9xq:-NTJDV323cmiXk1sZifz:b-f1av7i) ([raw file](https://github.com/eastgenomics/athena/blob/a368bfe19bd19695ae68faf586440f9d9e314b59/athena/athena.py#L165)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

there'll be more here right? else this looks redundant
</blockquote></details>

yeah was just mapping out whats coming in other PRs for structure in my head
___
*[`athena/bin/annotate.py` line 35 at r2](https://reviewable.io/reviews/eastgenomics/athena/84#-NTITPC_3JkEl9zWXgeQ:-NTJDu9y5XqFuXVWT9Cq:berrx98) ([raw file](https://github.com/eastgenomics/athena/blob/a368bfe19bd19695ae68faf586440f9d9e314b59/athena/bin/annotate.py#L35)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

it's weird to read bedtool
</blockquote></details>

this is the pybedtools syntax weirdness
___
*[`athena/bin/annotate.py` line 80 at r2](https://reviewable.io/reviews/eastgenomics/athena/84#-NTIlvLx6zP7ifitvV4C:-NTKIPL--A5qfsdFtgKu:b-ygw6zl) ([raw file](https://github.com/eastgenomics/athena/blob/a368bfe19bd19695ae68faf586440f9d9e314b59/athena/bin/annotate.py#L80)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

might be better just to standardize the function to accept list[pd.DataFrame] rather than either list of df or df. Then deal with it with a for loop in both if else statement below since if not chunks, there'll only be one df in the list thus looped through once.
</blockquote></details>

I've rewritten how all of this is done to remove the need to read everything into dataframes and directly use the file to make it a lot simpler and faster
___
*[`athena/bin/annotate.py` line 138 at r2](https://reviewable.io/reviews/eastgenomics/athena/84#-NTIUBji2fw8i6rfDIpy:-NTJE79W1tUY7aPDL8as:bdrq07w) ([raw file](https://github.com/eastgenomics/athena/blob/a368bfe19bd19695ae68faf586440f9d9e314b59/athena/bin/annotate.py#L138)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

is there no error message if the issue is a memory limit?
</blockquote></details>

pretty sure not, I think when it happened before pybedtools just failed but didn't raise an exception, I'll go get a chunky file too test with and see if it does
___
*[`athena/bin/arguments.py` line 25 at r2](https://reviewable.io/reviews/eastgenomics/athena/84#-NTIUVjE6jBRMUpVE37O:-NTJFdfE4_fr5_YmFQoS:b-896fix) ([raw file](https://github.com/eastgenomics/athena/blob/a368bfe19bd19695ae68faf586440f9d9e314b59/athena/bin/arguments.py#L25)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

no info on arg
</blockquote></details>

Done.
___
*[`athena/bin/utils.py` line 42 at r2](https://reviewable.io/reviews/eastgenomics/athena/84#-NTIuuou8zPvB7wJiKcD:-NTJGR1mBq9H1HnepIuR:b-xcratr) ([raw file](https://github.com/eastgenomics/athena/blob/a368bfe19bd19695ae68faf586440f9d9e314b59/athena/bin/utils.py#L42)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

is this generating
```
    chr  exon_start exon_end  gene      tx         exon cov_start  cov_end  cov position
    1    2488098    2488177  TNFRSF14  NM_003820.3  1    2488096   2488099  233 [2488096, 2488097, 2488098....]
```

</blockquote></details>

yep exactly, this is because the raw coverage data is binned by adjacent bases that have the same coverage (which here is `cov_start` and `cov_end`) to then calculate values we need these back to single rows for each position which is what this and `.explode()` does
___
*[`athena/bin/load.py` line 59 at r2](https://reviewable.io/reviews/eastgenomics/athena/84#-NTIo0RA6ABGrt-dDFjM:-NTJIPHK7KlWD06M8AmC:b9mv1hd) ([raw file](https://github.com/eastgenomics/athena/blob/a368bfe19bd19695ae68faf586440f9d9e314b59/athena/bin/load.py#L59)):*
`readline()` returns a string of the first line, `readlines()` reads the whole file and returns a list of strings

```
>>> with open('requirements.txt') as f:
...     line = f.readline()
...     f.seek(0)
...     lines = f.readlines()
... 
0
>>> line
'cycler==0.10.0\n'
>>> len(lines)
12
>>> lines[:2]
['cycler==0.10.0\n', 'kiwisolver==1.2.0\n']
```
___
*[`athena/bin/load.py` line 71 at r2](https://reviewable.io/reviews/eastgenomics/athena/84#-NTInOXh9nPP_m04ts-8:-NTJJAns8I6RhBc8PiTq:b-896fix) ([raw file](https://github.com/eastgenomics/athena/blob/a368bfe19bd19695ae68faf586440f9d9e314b59/athena/bin/load.py#L71)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

could do .strip() afterward just in case there're some outlier which end up with additional empty space after .replace()
</blockquote></details>

Done.
___
*[`athena/bin/load.py` line 99 at r2](https://reviewable.io/reviews/eastgenomics/athena/84#-NTIoWIh9h9xMehSFxSK:-NTJJB_E4tIKCjvGBBw6:b-896fix) ([raw file](https://github.com/eastgenomics/athena/blob/a368bfe19bd19695ae68faf586440f9d9e314b59/athena/bin/load.py#L99)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

do a .strip() to eliminate potential empty space after replace
</blockquote></details>

Done.
___
*[`athena/bin/load.py` line 105 at r2](https://reviewable.io/reviews/eastgenomics/athena/84#-NTIol830pc9IWVlAZ2q:-NTKILD3AlBu7nHOb3GN:b3ksc) ([raw file](https://github.com/eastgenomics/athena/blob/a368bfe19bd19695ae68faf586440f9d9e314b [...]

2023-04-19 09:03 UTC, JasonLing95 reviewed
> Reviewed 4 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/athena/84)* status: 28 of 32 files reviewed, 12 unresolved discussions (waiting on @jethror1 and @Yu-jinKim)

___
*[`athena/bin/load.py` line 59 at r2](https://reviewable.io/reviews/eastgenomics/athena/84#-NTIo0RA6ABGrt-dDFjM:-NTNjhKU83DYoRiLToh2:b-16b3sp) ([raw file](https://github.com/eastgenomics/athena/blob/a368bfe19bd19695ae68faf586440f9d9e314b59/athena/bin/load.py#L59)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

`readline()` returns a string of the first line, `readlines()` reads the whole file and returns a list of strings

```
>>> with open('requirements.txt') as f:
...     line = f.readline()
...     f.seek(0)
...     lines = f.readlines()
... 
0
>>> line
'cycler==0.10.0\n'
>>> len(lines)
12
>>> lines[:2]
['cycler==0.10.0\n', 'kiwisolver==1.2.0\n']
```
</blockquote></details>

I see, my brain was thinking of readlines()


<!-- Sent from Reviewable.io -->

2023-04-19 09:12 UTC, JasonLing95 reviewed
> Reviewed 3 of 8 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/athena/84)* status: all files reviewed, 12 unresolved discussions (waiting on @jethror1 and @Yu-jinKim)



<!-- Sent from Reviewable.io -->

2023-04-19 09:14 UTC, JasonLing95 requested changes
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/athena/84)* status: all files reviewed, 13 unresolved discussions (waiting on @jethror1 and @Yu-jinKim)

___
*[`athena/bin/annotate.py` line 146 at r4](https://reviewable.io/reviews/eastgenomics/athena/84#-NTNmbWwDP2_2DbtYJ8X:-NTNmbWwDP2_2DbtYJ8Y:b-dli36c) ([raw file](https://github.com/eastgenomics/athena/blob/7e0f57e371f52124689f6867f7f23ccf22bce9b9/athena/bin/annotate.py#L146)):*
> ```Python
>         assert len(bed_w_coverage.index) > 0, (
>             "Error calling bedtools to intersect per base coverage data with "
>             "panel bed, this is likely due to running out of available memory"
> ```

will there be possibility of bedtools success run which result in empty df generated?



_Code quote:_
```Python
 "panel bed, this is likely due to running out of available memory"
```


<!-- Sent from Reviewable.io -->

2023-04-19 09:53 UTC, jethror1 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/athena/84)* status: all files reviewed, 13 unresolved discussions (waiting on @JasonLing95 and @Yu-jinKim)

___
*[`athena/bin/annotate.py` line 146 at r4](https://reviewable.io/reviews/eastgenomics/athena/84#-NTNmbWwDP2_2DbtYJ8X:-NTNuxhI0py_wZvRyukO:bdfr9q5) ([raw file](https://github.com/eastgenomics/athena/blob/7e0f57e371f52124689f6867f7f23ccf22bce9b9/athena/bin/annotate.py#L146)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

will there be possibility of bedtools success run which result in empty df generated?
</blockquote></details>

not if the correct files are passed no, it intersects the bed file for the panel (chrom, start, end, transcript) against another file with gene symbols and exon numbers for each transcript to add in what genes and exons are included in the given panel bed file, if nothing matches it will be an empty file but this will mean something has gone wrong
___
*[`athena/bin/load.py` line 339 at r2](https://reviewable.io/reviews/eastgenomics/athena/84#-NTIr4er45yAGRT3UrYo:-NTNudcA7pyqI1IvrGl7:befh9r9) ([raw file](https://github.com/eastgenomics/athena/blob/a368bfe19bd19695ae68faf586440f9d9e314b59/athena/bin/load.py#L339)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

can these two be one if clause? will there be a possibility that there's no 37 in reference?
</blockquote></details>

this was just for displaying ref string in the report, I've removed this for now until I get to rewriting the report bu passing a reference build will be a required argument, so this can go


<!-- Sent from Reviewable.io -->

2023-04-19 13:11 UTC, JasonLing95 reviewed
> Reviewed 1 of 1 files at r5, 12 of 12 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/athena/84)* status: all files reviewed, 11 unresolved discussions (waiting on @jethror1 and @Yu-jinKim)



<!-- Sent from Reviewable.io -->

2023-04-20 12:33 UTC, Yu-jinKim requested changes
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/athena/84)* status: all files reviewed, 3 unresolved discussions (waiting on @jethror1)

___
*[`README.md` line 29 at r7](https://reviewable.io/reviews/eastgenomics/athena/84#-NTTcWBDAHSAHB2Cf-VS:-NTTcWBDAHSAHB2Cf-VT:b3plgsu) ([raw file](https://github.com/eastgenomics/athena/blob/f4612dc7898eddbcb65d042e9adef603959c62cd/README.md#L29)):*
> ```Markdown
> - Generate HTML coverage report with `coverage_report_single.py`
> 
> For DNAnexus cloud platform users, an Athena [dx applet][dx-url] has also been built.
> ```

is it still an applet?
___
*[`README.md` line 57 at r7](https://reviewable.io/reviews/eastgenomics/athena/84#-NTTcq1gBVmaFVjkHiag:-NTTcq1gBVmaFVjkHiah:bb7phvt) ([raw file](https://github.com/eastgenomics/athena/blob/f4612dc7898eddbcb65d042e9adef603959c62cd/README.md#L57)):*
> ```Markdown
> -c / --coverage_file : Per base coverage file (output from mosdepth or similar)
> 
> -s / -chunk_size : (optional) nrows to split per-base coverage file for intersecting, with <16GB RAM can lead to bedtools intersect failing. Reccomended values: 16GB RAM -> 20000000; 8GB RAM -> 10000000
> ```

typo


<!-- Sent from Reviewable.io -->

2023-04-20 12:52 UTC, JasonLing95 reviewed
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/athena/84)* status: all files reviewed, 3 unresolved discussions (waiting on @jethror1 and @Yu-jinKim)

___
*[`README.md` line 29 at r7](https://reviewable.io/reviews/eastgenomics/athena/84#-NTTcWBDAHSAHB2Cf-VS:-NTTi1U8EVJr_J88bTcU:b-763yc6) ([raw file](https://github.com/eastgenomics/athena/blob/f4612dc7898eddbcb65d042e9adef603959c62cd/README.md#L29)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

is it still an applet?
</blockquote></details>

will it be more comprehensive also to include example cmd to run dnanexus applet and  whatever parameters it require in the dx cmd?


<!-- Sent from Reviewable.io -->

2023-04-20 14:59 UTC, jethror1 reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/athena/84)* status: 32 of 37 files reviewed, 3 unresolved discussions (waiting on @JasonLing95 and @Yu-jinKim)

___
*[`README.md` line 29 at r7](https://reviewable.io/reviews/eastgenomics/athena/84#-NTTcWBDAHSAHB2Cf-VS:-NTU8fVGELEFjkav1DXZ:brja67i) ([raw file](https://github.com/eastgenomics/athena/blob/f4612dc7898eddbcb65d042e9adef603959c62cd/README.md#L29)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

will it be more comprehensive also to include example cmd to run dnanexus applet and  whatever parameters it require in the dx cmd?
</blockquote></details>

I'm going to rewrite the readme when I've done more changes since its going to all be different with how it runs (and hopefully I can add the dx app code into here too to have it in one repo), might just delete the readme for now
___
*[`README.md` line 57 at r7](https://reviewable.io/reviews/eastgenomics/athena/84#-NTTcq1gBVmaFVjkHiag:-NTU8tzcDR2OVlkeXl6l:b-yeec3j) ([raw file](https://github.com/eastgenomics/athena/blob/f4612dc7898eddbcb65d042e9adef603959c62cd/README.md#L57)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

typo
</blockquote></details>

gonna delete the readme until everything is ready and rewrite
___
*[`athena/bin/load.py` line 15 at r2](https://reviewable.io/reviews/eastgenomics/athena/84#-NTImoDd7uw18baL2VVU:-NTUAHS9EP2-H6ylq6hr:b-896fix) ([raw file](https://github.com/eastgenomics/athena/blob/a368bfe19bd19695ae68faf586440f9d9e314b59/athena/bin/load.py#L15)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

LoadData()
</blockquote></details>

Done.
___
*[`athena/bin/load.py` line 87 at r2](https://reviewable.io/reviews/eastgenomics/athena/84#-NTIWtXkARL9DpFBjCTb:-NTUAGP72eDca6eDkoP1:b-hpvc3e) ([raw file](https://github.com/eastgenomics/athena/blob/a368bfe19bd19695ae68faf586440f9d9e314b59/athena/bin/load.py#L87)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

is that correct based on the error message?
</blockquote></details>

nope, changed it


<!-- Sent from Reviewable.io -->

2023-04-20 15:02 UTC, Yu-jinKim approved these changes
> Reviewed 5 of 5 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/athena/84)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jethror1)



<!-- Sent from Reviewable.io -->

2023-04-20 15:02 UTC, JasonLing95 approved these changes
> Reviewed 5 of 5 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/athena/84)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jethror1)



<!-- Sent from Reviewable.io -->

2023-04-20 15:04 UTC, JasonLing95 commented
is there more commits or this pr can be merged? @jethror1

2023-04-20 15:04 UTC, merged